[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src\\bin\\06\\06.rs"
name = "06"
test = false
bench = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"